### ISSUE TITLE
Puppet Repo?

### ISSUE THREAD

**Issue by thejefflarson** [deaddrop/DeadDropDocs#2]
Are there plans in the works to open source deaddrop_puppet? This line doesn't work:

git clone https://github.com/deaddrop/deaddrop_puppet

**Comment by dolanjs** [comment]
Yes, fixing some typos and will be making it public later today.

**Comment by thejefflarson** [comment]
Hate to be a nag, but we are really looking forward to setting one of these up at ProPublica, is there an ETA on this ticket? Or is there another way to set it up?

**Comment by dolanjs** [comment]
Not nagging, it had to be updated for a few of the other changes that were recently made. Right now there are issues with it tha I'll add to issue list. The puppetlabs-apache module overwrites the docroot so you will have to manually copy the deaddrop/static folder after the manifest is run the first time. And ensure that correct ssh key are added to the known hosts file.

**Comment by thejefflarson** [comment]
Thanks!
