### ISSUE TITLE
Consider using single packet authentication on all non-publicly exposed servers & services

### ISSUE THREAD

**Issue by djon3s** [deaddrop/DeadDropDocs#4]
The advantage of using single packet authentication is to evade port scanning which may allow an attacker to determine the services running on the computer and perhaps gain enough information to determine the location of the non-public servers thus bringing some physical attacks into play.

**Comment by ioerror** [comment]
I suggest the use of a Tor Hidden Service in Stealth configuration - it is better than SPA in almost every sense:

```
       HiddenServiceAuthorizeClient auth-type client-name,client-name,...
           If configured, the hidden service is accessible for authorized
           clients only. The auth-type can either be 'basic' for a
           general-purpose authorization protocol or 'stealth' for a less
           scalable protocol that also hides service activity from
           unauthorized clients. Only clients that are listed here are
           authorized to access the hidden service. Valid client names are 1
           to 19 characters long and only use characters in A-Za-z0-9+-_ (no
           spaces). If this option is set, the hidden service is not
           accessible for clients without authorization any more. Generated
           authorization data can be found in the hostname file. Clients need
           to put this authorization data in their configuration file using
           HidServAuth.
```

**Comment by dolanjs** [comment]
If we do move off VPN for the journalist access to journalist interface and admin access to the environment then we would look at the stealthy hidden service. Closing this ticket letting it roll up in ioerror's other issue #6
